import type { Metadata } from "next";
import localFont from "next/font/local";
// import "./globals.css";
import { Toaster } from "@/components/ui/toaster"
import NavbarComponent from "@/components/NavbarComponent";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body>
          <NavbarComponent />
          {children}
          <Toaster />
        </body>
    </html>
  );
}
